### ISSUE TITLE
Trunk rv. 1056 does not build on Mac OS X 10.5.5

### ISSUE THREAD

**Issue by richard42** [mupen64plus/mupen64plus-user-issues#146]
Originally reported on Google Code with ID 146

```
Describe your system:
 - Mac OS X 10.5.5 w/ Xquartz 2.1.5 - (xorg-server 1.3.0-apple22) (2.1.5)
on an Intel Macbook
 - Machine type: 32
 - Mupen64Plus version: Trunk rv. 1056
- Plugins used:

Describe the problem:

Trunk does not build on Mac OS X 10.5.5.  With the Makefile included in
SVN, the following occurs:

g++ main/main.o main/romcache.o main/util.o main/translate.o main/cheat.o
main/config.o main/adler32.o main/md5.o main/plugin.o main/rom.o
main/savestates.o main/zip/ioapi.o main/zip/unzip.o main/bzip2/bzlib.o
main/bzip2/crctable.o main/bzip2/decompress.o main/bzip2/compress.o
main/bzip2/randtable.o main/bzip2/huffman.o main/bzip2/blocksort.o
main/lzma/buffer.o main/lzma/io.o main/lzma/main.o main/7zip/7zAlloc.o
main/7zip/7zBuffer.o main/7zip/7zCrc.o main/7zip/7zDecode.o
main/7zip/7zExtract.o main/7zip/7zHeader.o main/7zip/7zIn.o
main/7zip/7zItem.o main/7zip/7zMain.o main/7zip/LzmaDecode.o
main/7zip/BranchX86.o main/7zip/BranchX86_2.o memory/dma.o
memory/flashram.o memory/memory.o memory/pif.o memory/tlb.o r4300/r4300.o
r4300/bc.o r4300/compare_core.o r4300/cop0.o r4300/cop1.o r4300/cop1_d.o
r4300/cop1_l.o r4300/cop1_s.o r4300/cop1_w.o r4300/exception.o
r4300/interupt.o r4300/profile.o r4300/pure_interp.o r4300/recomp.o
r4300/special.o r4300/regimm.o r4300/tlb.o r4300/x86/assemble.o
r4300/x86/debug.o r4300/x86/gbc.o r4300/x86/gcop0.o r4300/x86/gcop1.o
r4300/x86/gcop1_d.o r4300/x86/gcop1_l.o r4300/x86/gcop1_s.o
r4300/x86/gcop1_w.o r4300/x86/gr4300.o r4300/x86/gregimm.o
r4300/x86/gspecial.o r4300/x86/gtlb.o r4300/x86/regcache.o
r4300/x86/rjump.o opengl/OGLFT.o opengl/osd.o opengl/screenshot.o
main/gui_gtk/main_gtk.o main/gui_gtk/icontheme.o main/gui_gtk/aboutdialog.o
main/gui_gtk/cheatdialog.o main/gui_gtk/configdialog.o
main/gui_gtk/rombrowser.o main/gui_gtk/romproperties.o  -lz -lm -lpng
-lfreetype -L/opt/fink/lib -lSDLmain -lSDL -Wl,-framework,Cocoa -framework
OpenGL -Wl,-framework,CoreServices,-framework,ApplicationServices
-L/opt/fink/lib -L/usr/X11/lib -lgtk-x11-2.0 -lgdk-x11-2.0 -lXrandr
-lXinerama -lXext -lXfixes -lXcursor -latk-1.0 -lgdk_pixbuf-2.0
-lpangoxft-1.0 -lXft -lXrender -lpangox-1.0 -lX11 -lpangoft2-1.0
-lfontconfig -lfreetype -lz -lpango-1.0 -lm -lgobject-2.0 -lgmodule-2.0
-lglib-2.0 -lintl -liconv   -L/opt/fink/lib -lgthread-2.0 -lglib-2.0 -lintl
-liconv   -ldl -o mupen64plus
ld: cycle in dylib re-exports with /usr/X11/lib/libGL.dylib


This error is known to Apple, and a fix is suggested at
http://developer.apple.com/qa/qa2007/qa1567.html.  When such a patch is
applied to the Makefile, the following error occurs when Makeing all:

g++ main/main.o main/romcache.o main/util.o main/translate.o main/cheat.o
main/config.o main/adler32.o main/md5.o main/plugin.o main/rom.o
main/savestates.o main/zip/ioapi.o main/zip/unzip.o main/bzip2/bzlib.o
main/bzip2/crctable.o main/bzip2/decompress.o main/bzip2/compress.o
main/bzip2/randtable.o main/bzip2/huffman.o main/bzip2/blocksort.o
main/lzma/buffer.o main/lzma/io.o main/lzma/main.o main/7zip/7zAlloc.o
main/7zip/7zBuffer.o main/7zip/7zCrc.o main/7zip/7zDecode.o
main/7zip/7zExtract.o main/7zip/7zHeader.o main/7zip/7zIn.o
main/7zip/7zItem.o main/7zip/7zMain.o main/7zip/LzmaDecode.o
main/7zip/BranchX86.o main/7zip/BranchX86_2.o memory/dma.o
memory/flashram.o memory/memory.o memory/pif.o memory/tlb.o r4300/r4300.o
r4300/bc.o r4300/compare_core.o r4300/cop0.o r4300/cop1.o r4300/cop1_d.o
r4300/cop1_l.o r4300/cop1_s.o r4300/cop1_w.o r4300/exception.o
r4300/interupt.o r4300/profile.o r4300/pure_interp.o r4300/recomp.o
r4300/special.o r4300/regimm.o r4300/tlb.o r4300/x86/assemble.o
r4300/x86/debug.o r4300/x86/gbc.o r4300/x86/gcop0.o r4300/x86/gcop1.o
r4300/x86/gcop1_d.o r4300/x86/gcop1_l.o r4300/x86/gcop1_s.o
r4300/x86/gcop1_w.o r4300/x86/gr4300.o r4300/x86/gregimm.o
r4300/x86/gspecial.o r4300/x86/gtlb.o r4300/x86/regcache.o
r4300/x86/rjump.o opengl/OGLFT.o opengl/osd.o opengl/screenshot.o
main/gui_gtk/main_gtk.o main/gui_gtk/icontheme.o main/gui_gtk/aboutdialog.o
main/gui_gtk/cheatdialog.o main/gui_gtk/configdialog.o
main/gui_gtk/rombrowser.o main/gui_gtk/romproperties.o  -lz -lm -lpng
-lfreetype -Wl -dylib_file
/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib:/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
-L/opt/fink/lib -lSDLmain -lSDL -Wl,-framework,Cocoa -framework OpenGL
-Wl,-framework,CoreServices,-framework,ApplicationServices -L/opt/fink/lib
-L/usr/X11/lib -lgtk-x11-2.0 -lgdk-x11-2.0 -lXrandr -lXinerama -lXext
-lXfixes -lXcursor -latk-1.0 -lgdk_pixbuf-2.0 -lpangoxft-1.0 -lXft
-lXrender -lpangox-1.0 -lX11 -lpangoft2-1.0 -lfontconfig -lfreetype -lz
-lpango-1.0 -lm -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lintl -liconv  
-L/opt/fink/lib -lgthread-2.0 -lglib-2.0 -lintl -liconv   -ldl -o mupen64plus
Undefined symbols:
  "_iconv_close", referenced from:
      _fill_entry in romcache.o
      _tr_init in translate.o
  "_iconv", referenced from:
      _fill_entry in romcache.o
      _tr_init in translate.o
      _tr_init in translate.o
  "_iconv_open", referenced from:
      _fill_entry in romcache.o
      _tr_init in translate.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make: *** [mupen64plus] Error 1


```

Reported by `chrisjrn` on 2008-09-16 04:02:11

**Comment by richard42** [comment]
```
Looks like GNU libiconv isn't installed on your system.
```

Reported by `sknauert@wesleyan.edu` on 2008-09-16 20:53:00

**Comment by richard42** [comment]
```
Also, try using the non-X11 Gtk.
```

Reported by `sknauert@wesleyan.edu` on 2008-09-30 18:38:39

**Comment by richard42** [comment]
```
Closing, two users have gotten Mupen64Plus svn trunk to compile on OSX 10.5.5.
```

Reported by `sknauert@wesleyan.edu` on 2008-10-02 20:41:08

**Comment by richard42** [comment]
Reported by `sknauert@wesleyan.edu` on 2008-10-02 20:42:38
- **Status changed**: `Invalid`

**Comment by richard42** [comment]
Reported by `sknauert@wesleyan.edu` on 2008-10-02 20:42:39
